# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

before_script:
  - python -V  # Print out python version for debugging

test:
  script:
    - tox -e code-check
