name: Block Offensive Language
on: pull_request_target

jobs:
  offensive_language_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.sha }}

      - name: Run Action
        uses: myakove/set-labels@master
        with:
          token: ${{secrets.CNV_QE_BOT_TOKEN}}
          action: block_offensive_language
