name: Tox Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  tox-tests:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{github.event.pull_request.number}}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install tox-uv
      run: |
        uv tool install tox --with tox-uv

    - name: Run tox environments
      run: |
        tox
